//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "66c01b6cd702b9dbadc272af"
}
{
  "id": "66c020b15a79d7aa1d17339b"
}
{
  "id": "66c43d3bdac3314516378595"
}


###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test Testsson",
  "email": "test@mail.com",
  "password": "test"
}
{
  "name": "Marvin Marvsson",
  "email": "marv@sson.com",
  "password": "marvmarv"
}
{
  "name": "Kalle Anka",
  "email": "kalleanka@mail.com",
  "password": "kalleanka"
}
{
  "name": "Musse Pigg",
  "email": "mussepigg@mail.com",
  "password": "mussepigg"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "mussepigg@mail.com",
  "password": "mussepigg"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/66c79d183be53b5eb77f2f34

  {
        "_id": "66c79d183be53b5eb77f2f34",
        "name": "Blueberry milkshake",
        "description": "Milkshake with a taste of blueberries",
        "price": 80,
        "lager": 10
    }
///
{
    "_id": "66c7a1d45a1b6cf146eb0e55",
    "name": "Maräng",
    "description": "Rosa maräng med en touch av socker",
    "price": 35,
    "lager": 8
}
###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 1",
  "description": "Beskrivning av produkt 1",
  "price": 100, 
  "lager": 10
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
    "user": "{{getUsers.response.body.$[0].id}}",
    "products": [
        {
            "productId": "66c79d183be53b5eb77f2f34",
            "quantity": 1
        },
        {
            "productId": "66c7a1d45a1b6cf146eb0e55",
            "quantity": 2
        }
    ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

[
    {
        "user": "{{getUsers.response.body.$[0].id}}",
        "products": [
            {
                "productId": "66c79d183be53b5eb77f2f34",
                "quantity": 1
            },
            {
                "productId": "66c7a1d45a1b6cf146eb0e55",
                "quantity": 2
            }
        ],
        "id": "66c7a6a4e023e3c9bcb43e45"
    }
]
###